const allClubs = [
    {
        id: 0,
        name: 'Dance Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/danceLogo.png',
        email: 'dance@ahduni.edu.in',
        secretaryImage: 'assets/images/danceSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_danceclub/?igshid=6bi6mp9bgeij',
        secretaryName: "Sodha Dhruvi Bhavin",
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 1,
        name: 'Food Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/food.jpg',
        email: 'food.club@ahduni.edu.in',
        secretaryImage: 'assets/images/foodSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_foodclub/',
        secretaryName: 'Nikita Mukesh Padalia',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 2,
        name: 'Pclub',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/pclubLogo.png',
        email: 'programming.clib@ahduni.edu.in',
        secretaryImage: 'assets/images/pclubSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_programmingclub/',
        secretaryName: 'Kakkad Yashraj Mehul',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 3,
        name: 'Entrepreneur Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/entrepreneurLogo.png',
        email: 'entrepreneur.club@ahduni.edu.in',
        secretaryImage: 'assets/images/entrepreneurSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_entrepreneurs_club/?igshid=8uoo2op8vqtp',
        secretaryName: 'Harshvardhan Rajesh Jethani',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 4,
        name: 'Sports Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/sport.jpg',
        email: 'sportsclub@ahduni.edu.in',
        secretaryImage: 'assets/images/sportsSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_sportsclub/',
        secretaryName: 'Jai Hemang Bhatt',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 5,
        name: 'Fitness Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/fitnessLogo.png',
        email: 'fitness@ahduni.edu.in',
        secretaryImage: 'assets/images/fitnessSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_fitnessclub/',
        secretaryName: 'Haard Monpara',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 6,
        name: 'Photography Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/photography.png',
        email: 'photography.club@ahduni.edu.in',
        secretaryImage: 'assets/images/photographySecretary.jpg',
        link: 'https://www.instagram.com/ahduni_photographyclub/',
        secretaryName: 'Khush Kumanbhai Kalavadia',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 7,
        name: 'The Management Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/managementLogo.jpg',
        email: 'tmc@ahduni.edu.in',
        secretaryImage: 'assets/images/managementSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_danceclub/?igshid=6bi6mp9bgeij',
        secretaryName: 'Heer Rajesh Bhardwaj',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 8,
        name: 'Quiz Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/quiz.jpg',
        email: 'quiz.club@ahduni.edu.in',
        secretaryImage: 'assets/images/quizSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_quizclub/',
        secretaryName: 'Devarshi Hardik Rawal',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 9,
        name: 'Magazine Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/magazine.jpg',
        email: 'studentsmagazine@ahduni.edu.in',
        secretaryImage: 'assets/images/magazineSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_magazineclub/',
        secretaryName: 'Bansari Brahmbhatt',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 10,
        name: 'Environment Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/environment.jpg',
        email: 'environment.club@ahduni.edu.in',
        secretaryImage: 'assets/images/environmentSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_environmentclub/',
        secretaryName: 'Harsh M Kakasaniya',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 11,
        name: 'Fine Arts Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/fineArts.png',
        email: 'fine.arts@ahduni.edu.in',
        secretaryImage: 'assets/images/fineArtsSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_fineartsclub/',
        secretaryName: 'Radhika Bhavinbhai Contract',
                description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut laboredolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
    },
    {
        id: 12,
        name: 'Literary Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/literaryLogo.png',
        email: 'literary.club@ahduni.edu.in',
        secretaryImage: 'assets/images/literarySecretary.jpg',
        link: 'https://www.instagram.com/ahduni_literaryclub/',
        secretaryName: 'Udit Kapadia',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 13,
        name: 'Social Service Forum',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/socialService.jpg',
        email: 'social.service.forum@ahduni.edu.in',
        secretaryImage: 'assets/images/socialServiceForumSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_socialserviceforum/?igshid=1pxzsygdm4g5q',
        secretaryName: 'Piyush Jain',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 14,
        name: 'Theater',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/theater.jpg',
        email: 'theater@ahduni.edu.in',
        secretaryImage: 'assets/images/theaterSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_theatreclub/',
        secretaryName: 'Hitesh Bharatbhai Samariya',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 15,
        name: 'Heritage Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/heritage.jpg',
        email: 'heritage.club@ahduni.edu.in',
        secretaryImage: 'assets/images/heritageSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_sharitage/',
        secretaryName: 'Kavya Nair',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        id: 16,
        name: 'Music Club',
        image: 'assets/images/dance.jpg',
        logo: 'assets/images/music.jpg',
        email: 'music@ahduni.edu.in',
        secretaryImage: 'assets/images/musicSecretary.jpg',
        link: 'https://www.instagram.com/ahduni_musicclub/?igshid=4u2s86b21kdc',
        secretaryName: 'Saryu Nayak',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
];
export default allClubs;